---
title: " "
format: html
---

# Testes de Hipóteses

## Importar planilha de dados diversos

```{r}
library(gsheet)
mg <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=983033137")

```

## Vizualizar

```{r}
library(tidyverse)
library(ggthemes)


mg |> 
  ggplot(aes(trat, comp))+
  geom_boxplot(fill = "gray")+
  theme_few()

```

## Teste t para dois grupos de médias independentes

```{r}
#Passar os dados para o formato largo
mg2 <- mg |> 
  pivot_wider(names_from = trat, values_from = comp)
 
mg2

#Presupposes: normality and homogeneity of variance

shapiro.test(mg2$control) #No teste de shapiro a H0 é de que a distribuição é normal
hist(mg2$control)

shapiro.test(mg2$Mg2)
hist(mg2$Mg2)

var.test(mg2$control, mg2$Mg2)

qqnorm(mg2$control)
qqline(mg2$control)

#T test
teste1 <- t.test(mg2$control, mg2$Mg2) #Pode usar 'var.equal = FALSE' quando a variância for heterogênea

```

## Reportar o resultado

```{r}
library(report)
report(teste1)

```

## Teste t para dois grupos de médias dependentes

```{r}
escala <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1729131173")

#Vizualizar
escala |> 
  ggplot(aes(assessment, acuracia))+
  geom_boxplot(fill = "gray")+
  theme_few()

#Passar os dados para o formato largo
escala2 <- escala |> 
  select(assessment, rater, acuracia) |> 
  pivot_wider(names_from = assessment, values_from = acuracia)


 escala2


#Presupposes: normality and homogeneity of variance

shapiro.test(escala2$Unaided) #No teste de shapiro a H0 é de que a distribuição é normal
hist(escala2$Unaided)

qqnorm(escala2$Unaided)
qqline(escala2$Unaided)

shapiro.test(escala2$Aided1)
hist(escala2$Aided1)

qqnorm(escala2$Aided1)
qqline(escala2$Aided1)

#Homogeneidade de variância
var.test(escala2$Unaided, escala2$Aided1) #Ho é que a variância é homogênea


#T test
teste2 <- t.test(escala2$Unaided, escala2$Aided1,
                 paired = TRUE,
                 var.equal = FALSE) #Usar 'paired = TRUE' quando o teste t for pareado (média dependentes) e 'var.equal = FALSE' quando a variância for heterogêneanea

teste2

report(teste2)

```

## Teste T não paramétrico

```{r}
escala_np <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=1729131173")

#Vizualizar
escala_np |> 
  ggplot(aes(assessment, acuracia))+
  geom_boxplot(fill = "gray")+
  theme_few()

#Passar os dados para o formato largo
escala_np2 <- escala_np |> 
  select (assessment, rater, acuracia) |> 
  pivot_wider(names_from = assessment, values_from = acuracia)
 
escala_np2

#Presupposes: normality and homogeneity of variance

shapiro.test(escala_np2$Unaided) #No teste de shapiro a H0 é de que a distribuição é normal
hist(escala_np2$Unaided)

qqnorm(escala_np2$Unaided)
qqline(escala_np2$Unaided)

shapiro.test(escala_np2$Aided1)
hist(escala_np2$Aided1)

qqnorm(escala_np2$Aided1)
qqline(escala_np2$Aided1)

#Equivalente ao teste t não paramétrico = teste wilcox
teste3 <- wilcox.test(escala_np2$Unaided, escala_np2$Aided1, paired = TRUE)

teste3


```

```{r}
micelial <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=959387827")

#Vizualizar
micelial |> 
  ggplot(aes(especie, tcm))+
  geom_boxplot(fill = "gray")+
  geom_jitter(width = 0.1, size = 2)+
  theme_few()

anova_micelial <- aov(tcm ~ especie, data = micelial)
 
anova_micelial

summary(anova_micelial)
anova(anova_micelial)

anova_micelial2 <- lm(tcm ~ especie, data = micelial)

anova_micelial2
summary(anova_micelial2)
anova(anova_micelial2)


```


