## Regressão linear

```{r}
library(gsheet)
library(tidyverse)
library(ggthemes)
library(lme4)
library(r4pde)
library(broom)
library(car)
library(patchwork)
estande <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=401662555")

```

## Vizualizando

```{r}
 estande |> 
  ggplot(aes(trat, nplants))+
  geom_jitter(width = 0.1, alpha = 0.2)+
  #facet_wrap(~ exp)+
  stat_summary(fun.data = "mean_cl_boot", color = 'black', alpha = 0.5)+
  theme_few()+
  geom_smooth(method = "lm", se = F)

```

```{r}
exp1 = estande |> 
  filter(exp == 1)

exp1 |> 
  ggplot(aes(trat, nplants))+
  geom_point()+
  theme_few()+
  ylim(0,100)+
  geom_smooth(method = "lm", se = F)

# Modelo linear

lm1 <- lm(nplants ~ trat, data = exp1)

summary(lm1)

```

```{r}
exp2 = estande |> 
  filter(exp == 2)

exp2 |> 
  ggplot(aes(trat, nplants))+
  geom_point()+
  theme_few()+
  ylim(0,100)+
  geom_smooth(method = "lm", se = F)

# Modelo linear

lm2 <- lm(nplants ~ trat, data = exp2)

summary(lm2)

```

```{r}
exp3 = estande |> 
  filter(exp == 3)

exp3 |> 
  ggplot(aes(trat, nplants))+
  geom_point()+
  theme_few()+
  ylim(0,100)+
  geom_smooth(method = "lm", se = F)

# Modelo linear

lm3 <- lm(nplants ~ trat, data = exp3)

summary(lm3)

residuals(lm3)
hist(residuals(lm3))

```

```{r}
# Modelo linear generalizado
glm3 <- glm(nplants ~ trat,
            family = gaussian,
            data = exp3)

summary(glm3)
AIC(glm3)

glm3b <- glm(nplants ~ trat,
             family = poisson(link = "log"),
             data = exp3)

summary(glm3b)
AIC(glm3b) # 	Akaike's An Information Criterion (O Critério de Informação de Akaike": quanto menor, melhor)


# Modelos Lineares Generalizados de Efeitos Mistos

glmer3 <- glmer(nplants ~ trat + (trat | exp), family = gaussian, data = estande)

summary(glmer3)
AIC(glmer3)


glmer3b <- glmer(nplants ~ trat + (trat|exp), family = poisson(link = "log"),
                                                              data = estande) 

summary(glmer3b)
AIC(glmer3b) 

```

```{r}

wm <- WhiteMoldSoybean

wm |> 
  ggplot(aes(inc, yld, group = factor(study)))+
  geom_point()+
  #facet_wrap(~ study)+
  geom_smooth(method = "lm", se= F)
  theme_minimal()

```

```{r}

mofo1 <- lm(yld ~ inc,
            data = wm)

summary(mofo1)

```

```{r}
fit_all <- wm |> 
  group_by(study) |> 
  do(tidy(lm(.$yld ~ .$inc), conf.int = TRUE))

fit_all

g_inter <- fit_all |> 
  filter(term == "(Intercept)") |> 
  ggplot(aes(x = estimate))+
  theme_r4pde()+
  geom_histogram(bins = 8, color = "white", fill = "gray50")+
  labs(x = "Intercept", y = "frequency")

g_slop <- fit_all |> 
  filter(term == ".$inc") |> 
  ggplot(aes(x = estimate))+
  theme_r4pde()+
  geom_histogram(bins = 8, color = "white", fill = "gray50")+
  labs(x = "Slopes", y = "Frequency")


g_inter + g_slop

df <- fit_all |>
  filter(term == ".$inc")

mean(df$estimate)


```

```{r}
mofo2 <- lmer(yld ~ inc + (inc | study), data = wm,
              REML = F)

summary(mofo2)
Anova(mofo2)
confint(mofo2, method = "Wald")

```

## Aula - 29/05/2024

```{r}
library(tidyverse)
library(AgroR)
library(ec50estimator)
library(gsheet)
library(drc)
library(patchwork)
library(corrplot)
library(ggthemes)

```

```{r}
imgs <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=373270992")

```

```{r}
imgs |> 
  pivot_longer(3:5, names_to = "method",
               values_to = "value") |> 
  ggplot(aes(method, value))+
  geom_boxplot()

img1 <- imgs |> 
  ggplot(aes(Assess, LeafDoctor))+
  geom_point()+
  geom_smooth(method = "lm")

    
 img2 <- imgs |> 
   ggplot(aes(Assess, ImageJ))+
   geom_point()+
   geom_smooth(method = "lm")
 
  img3 <- imgs |> 
   ggplot(aes(ImageJ, LeafDoctor))+
   geom_point()+
   geom_smooth(method = "lm")

 img1 + img2 + img3

```

```{r}
imgs2 <- imgs |> 
  dplyr::select(3:5)

  corgraph(imgs2)
  
  cor.test(imgs$Assess, imgs$LeafDoctor)
  cor(imgs$Assess, imgs$LeafDoctor)

```

```{r}
cor_imgs2 <- cor(imgs2)
corrplot(cor_imgs2, method = "number", type = "lower")


```

```{r}
campo <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=866852711")

campo2 <- campo |> 
  dplyr::select(DFC, FER, PROD)

corgraph(campo2)


```

## Pós-intervalo

```{r}
campo |> 
  ggplot(aes(DFC, PROD))+
  geom_jitter()

```

```{r}
estande <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=401662555")

exp2 <- estande |> filter(exp == 2)

exp2 |> 
  ggplot(aes(trat, nplants))+
  geom_point()+
  theme_few()+
  ylim(0, 100)+
  geom_smooth(method = "lm",
              se = F,
              formula = y~poly(x,2),
              color = "red")+
  geom_smooth(method = "lm", se = FALSE)

#Modelo de primeira ordem
lm2 <- lm(nplants~trat,
          data = exp2)

summary(lm2)
hist(residuals(lm2))

# Modelo de segunda ordem ou modelo quadrático (ainda é um modelo liner, é um modelo curvelinear)
exp2$trat2 <- exp2$trat^2

lm3 <- lm(nplants~trat + trat2,
          data = exp2)

summary(lm3)
hist(residuals(lm3))


AIC(lm2)
AIC(lm3)


with(exp2, polynomial(trat, nplants, grau = 2))


#AgroR::polynomial(trat, nplants, grau = 1, data = exp2) # Não deu certo, não sei o pq

```

## Modelo não linear

```{r}
sensi <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1bq2N19DcZdtax2fQW9OHSGMR0X2__Z9T/edit#gid=465348652")

sensi$dose <- as.factor(sensi$dose)

is.factor(sensi$dose)

sensi|> 
  group_by(code, dose) |> 
  summarise(mean_germination = mean(germination)) |>  
  ggplot(aes(dose, mean_germination))+
  geom_point()+
  facet_wrap(~code)

```

```{r}
sensi2 <- sensi|> 
  group_by(code, dose) |> 
  summarise(mean_germination = mean(germination))

FGT05 <- sensi2 |> 
  filter(code == "FGT05")
 

library(drc)

#drc1 <- drm(mean_germination ~ dose, data = FGT05, fct = LL.3())

```